blog/urls.py
from django.conf.urls import patterns, url
# # from blog.rss import RssFeed

urlpatterns = patterns('',
    url(r'^$', 'blog.views.index', name='index'),
    url(r'^login/$', 'blog.views.login', name='login'),
    url(r'^sign_up/$', 'blog.views.sign_up', name='sign_up'),
    url(r'^sign_up_done/$', 'blog.views.sign_up_done', name='sign_up_done'),
    url(r'^login_done/$', 'blog.views.login_done', name='login_done'),
    # url(r'^blog_pg/$', 'blog.vi	ews.blog_pg', name='blog_pg'),
    url(r'^blog_list$', 'blog.views.blog_list', name='blog_list'),
    url(r'^logout_first/$','blog.views.logout_first', name='logout_first'),
    url(r'^logout/$','blog.views.logout',name='logout'),
    url(r'^logout_done/$','blog.views.logout_done',name='logout_done'),
    url(r'^add_blog/$','blog.views.add_blog',name='add_blog'),
    url(r'^add_blog_done/$','blog.views.add_blog_done',name='add_blog_done'),
    url(r'^login_first/$','blog.views.login_first',name='login_first'),
    url(r'^blog_pg/(?P<blog_id>\d+)/(?P<page_id>\d+)/$','blog.views.blog_pg',name='blog_pg'),
    url(r'^post_pg/(?P<post_id>\d+)/$','blog.views.post_pg',name='post_pg'),
    url(r'^tag/(?P<tag_id>\d+)/(?P<page_id>\d+)/$','blog.views.tag',name='tag'),
    url(r'^add_post/(?P<blog_id>\d+)/$','blog.views.add_post',name='add_post'),
    url(r'^add_post_done/(?P<blog_id>\d+)/$','blog.views.add_post_done',name='add_post_done'),

)

myblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    #url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.core.urlresolvers import reverse

class Blog(models.Model):
	usr=models.ForeignKey(User)
	name=models.CharField(max_length=50)		
	def __unicode__(self):
		return self.name

class Post(models.Model):
	blog=models.ForeignKey(Blog)
	title = models.CharField(max_length=50)
#	slug = models.SlugField(uniq=True, max_length=255)
	content = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	def __unicode__(self):
		return self.name

#	class Meta:
#		ordering = ['-created']
#	def get_absolute_url(self):
#		return reverse('blog.views.post', args=[self.slug])
	
class Tag(models.Model):
	post = models.ForeignKey(Post)
	tag = models.CharField(max_length=50)
	def __unicode__(self):
		return self.tag

class Timestamp(models.Model):
	post = models.ForeignKey(Post)
	time_modified = models.DateTimeField(auto_now=True)
	def __unicode__(self):
		return self.time_modifie
# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from blog.models import Blog, Post, Tag, Timestamp
from django.utils import timezone
# import re
# from xml.sax.saxutils import unescape
# from .forms import UploadFileForm

def index(request):
	user_name=request.user.username
	user_id=request.user.id
	blog_list = Blog.objects.all()
	# return HttpResponse("Hi")
	context={'blog_list':blog_list,'user_id':user_id,'user_name':user_name}
	return render(request, 'blog/index.html', context)

def sign_up(request):
	return render(request, 'blog/sign_up.html')

def login(request):
	if request.user.id:
		return render(request, 'blog/logout_first.html')
	else:
		return render(request, 'blog/login.html')

def logout_first(request):
	return render(request, 'blog/logout_first.html')

def sign_up_done(request):

    user_name = request.POST['user_name']
    password = request.POST['password']
    blog_name = request.POST['blog_name']
    try:
    	user = User.objects.create_user(user_name,password=password)
    except:
    	msg = "User Name Already Exists."
    	return render(request, 'blog/sign_up_done.html', {'msg':msg})
    else:
    	user=authenticate(username=user_name,password=password)
    	auth_login(request,user)
    	b=Blog(usr=request.user,name=blog_name)
    	b.save()
    	msg = "Successfully Signed Up!"
    	return render(request, 'blog/sign_up_done.html', {'msg':msg})

def login_done(request):
    username=request.POST['username']
    password=request.POST['password']
    user=authenticate(username=username,password=password)
    if user is not None:
		if user.is_active:
			msg="Successful Login"
			auth_login(request,user)
			return render(request, 'blog/login_done.html',{'msg':msg})
		else:
			msg="Disabled Account"
			return render(request, 'blog/login_done.html',{'msg':msg})
    else:
        msg="Invalid User Name or Password"
        return render(request, 'blog/login_done.html', {'msg':msg})

def login_first(request):
	return render(request, 'blog/login_first.html')

def logout(request):
	return render(request, 'blog/logout.html')

def logout_done(request):
	username=request.user.username
	auth_logout(request)
	return render(request, 'blog/logout_done.html',{'username':username})

def add_blog(request):
	return render(request, 'blog/add_blog.html')

def add_blog_done(request):
	blog_name=request.POST['blog_name']
	b=Blog(usr=request.user,name=blog_name)
	b.save()
	return render(request, 'blog/add_blog_done.html')

def blog_list(request):
	user_id=request.user.id
	if user_id is None:
		return render(request, 'blog/login_first.html')
	else:
		blog_list = Blog.objects.filter(usr_id = user_id)
		usr_name = request.user.username
		context={'usr_name':usr_name,'blog_list':blog_list}
		return render(request, 'blog/blog_list.html', context)

def blog_pg(request, blog_id, page_id):
	username=request.user.username
	blog=get_object_or_404(Blog,pk=blog_id)
	blog_name=blog.name
	post_list=blog.post_set.all()
	num_post=post_list.count()
	num_page=num_post/10
	context={'num_page':num_page,'blog_id':blog_id,'blog_name':blog_name,'post_list':post_list}
	return render(request, 'blog/blog_pg.html',context)

def post_pg(request, post_id):
	post=get_object_or_404(Post,pk=post_id)
	return render(request, 'blog/post_pg.html',{'post':post})

def tag(request, tag_id, page_id):
	return render(request, 'blog/tag.html')

def add_post(request, blog_id):
	user_id=request.user.id
	blog=Blog.objects.get(id=blog_id)
	content={'user_id':user_id,'blog':blog,'blog_id':blog_id}
	return render(request, 'blog/add_post.html',content)

def add_post_done(request, blog_id):
	title=request.POST['title']
	tag=request.POST['tag']
	content=request.POST['body']
	blog=get_object_or_404(Blog,pk=blog_id)
	post=Post(blog=blog,title=title,content=content,created=timezone.now())
	post.save()
	context={'blog_id':blog_id,'blog':blog}
	return render(request, 'blog/add_post_done.html',context)

# Create your views here.

blog/templates/blog/add_blog.html
<h1>You Can Add A Blog Here.</h1><br>
<form action="{% url 'blog:add_blog_done' %}" method="post">
{% csrf_token %}
Blog Name: <input type="text" name="blog_name"><br>
<input type="submit" value="Submit" />
</form>

blog/templates/blog/add_post.html
{% if user_id = blog.usr.id %}

	<h1>You can add a new post here.</h1><br>
	<form action="{% url 'blog:add_post_done' blog_id %}" method="post" id="addpost">
	{% csrf_token %}
	<p>Title:</p> <input type="text" name="title"><br>
	<p>Tag:</p> <input type="text" name="tag"><br>
	<p>Content:</p>  
	<textarea rows="20" cols="50" name="body" form="addpost"></textarea><br><br>
	<input type="submit" value="Submit" />
	</form>

{% else %}
	<h1>Sorry, you are not the owner of this blog.</h1><br>
	<a href="{% url 'blog:blog_pg' blog_id 0 %}">Let's go back to the blog.</a>
{% endif %}

blog/templates/blog/add_post_done.html
<h1>Post successfully submitted.</h1>
<a href="{% url 'blog:blog_pg' blog_id 0 %}">Go back to the blog.</a>

blog/templates/blog/blog_list.html
<h1>This is {{usr_name}}'s list of blogs</h1><br> 
<h3><a href="{% url 'blog:add_blog' %}">Add A Blog</a><br>
{%  if blog_list %}
<ul>
{% for blog in blog_list %}
	<li><a href="{%  url 'blog:blog_pg' blog.id 0 %}">{{ blog.name }}</a></li>
{% endfor %}
</ul>
{% else %}
	<p>No posts are available</p>
{% endif %}
<a href="{%url 'blog:index' %}">Go Back To The Main Page</a>

blog/templates/blog/blog_pg.html
<h1>{{blog_name}} </h1><br>
<a href="{% url 'blog:add_post' blog_id %}">Add Post</a><br>
{% for post in post_list %}
<ul>
	<li><a href="{% url 'blog:post_pg' post.id %}">{{post.title}}</a></li>
	{% for tag in post.tag_set.all %}
		{{tag.tag}},
	{% endfor %}
	<li>{{post.content}}</li>
	<li>{{post.created}}</li>
</ul>
{% endfor %}

blog/templates/blog/index.html
{% if user_name %}
<h1> Blog  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Login User: {{user_name}}</h1><br>
{% else %}
<h1> Blog </h1><br>
{% endif %}

<a href="{% url 'blog:blog_list' %}">My List of Blogs</a><br>

<a href = "{% url 'blog:sign_up' %}"> Sign Up </a> <br>
<a href = "{% url 'blog:login' %}"> Login </a> <br>
<a href = "{% url 'blog:logout' %}"> Logout </a> <br>

{%  if blog_list %}
	<ul>
	{% for blog in blog_list %}
		<li><a href="{%  url 'blog:blog_pg' blog.id 0 %}">{{ blog.name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No posts are available</p>
{% endif %}

blog/templates/blog/login.html
<h1>Login</h1><br>

<form action="{% url 'blog:login_done'%}" method="post">
{% csrf_token %}
User Name: <input type="text" name="username"><br>
Password:  <input type="password" name="password">
<input type="submit" value="Login" />
</form>

blog/templates/blog/login_first.html
<h1>Sorry, You Have To Login First.</h1><br>
<a href="{% url 'blog:index' %}">Let's Take You Back To The Main Page</a>

blog/templates/blog/logout_done.html
<h1>{{username}}, You Have Successfully Logged Out</h1>
<a href="{% url 'blog:index' %}">Go Back To The Main Page</a><br>

blog/templates/blog/logout_first.html
<h1>You Have To Logout First</h1>
<a href="{% url 'blog:index' %}">Go Back To The Main Page</a>

blog/templates/blog/post_pg.html
<h2>{{post.title}}</h2><br>
{% for tag in post.tag_set.all %}
	<h4>{{tag.tag}}</h4>
{% endfor %}
<br>
<p>{{post.content}}</p>
<h4>Time created: {{post.created}}</h4><br>
{% for time in post.timestamp_set.all %}
	<h4>{{time.time_modified}}</h4><br>
{% endfor %}
<a href="{% url 'blog:blog_pg' post.blog.id 0 %}">Go back to the blog.</a>

blog/templates/blog/sign_up.html
<h2>Sign Up</h2>
<form action="{% url 'blog:sign_up_done' %}" method="post">
{% csrf_token %}
Username: <input type="text" name="user_name"></input><br><br>
Password: <input type="password" name="password"></input><br><br>
Blog Name: <input type="text" name="blog_name"></input><br><br>
<input type="submit" value="Sign Up" />
</form>

blog/templates/blog/sign_up_done.html
{% if msg == "User Name Already Exists." %}
	<h2>{{msg}}</h2><br>
	<a href="{% url 'blog:sign_up' %}">Go Back To Sign Up</a><br>
{% else %}
	<h2>{{msg}}</h2><br>
	<h2><a href="{% url 'blog:blog_list'%} ">Go To Your List Of Blogs</a><br></h2>
{% endif %}
<a href="{% url 'blog:index' %}">Go back to the main page.</a>

blog/templates/blog/tag.html
<h1>Test tag html.</h1>